title: Windows Active Directory Pentest
description: Full Windows Active Directory Pentest Playbook
category: AD

blocks: 
  - name: AD General Information Gathering
    description: Gathering information about the AD environment helps to understand its structure and 
      get basic information about users, computers, services, and policies. It gives an overview of the layout, 
      interconnections, and dependencies between these entities. This part is crucial and should not be skipped.
      
    tests:
      - name: Bloodhound
        description: Automated AD enumeration using Bloodhound
        techniques:
          - id: t-ad-enumeration-bloodhound

      - name: PingCastle
        description: Automated AD enumeration using PingCastle
        techniques:
          - id: t-ad-enumeration-pingcastle
      
      - name: ADRecon.ps1
        description: Automated AD enumeration using ADRecon.ps1 script
        techniques:
          - id: t-ad-enumeration-adrecon_ps1

      - name: Manual Enumeration
        description: Manual basic enumeration (users, hosts, groups, trusts, policies, dns records) and making lists.
        techniques:
          - id: t-ad-enumeration-ad_enumeration_basics
          - id: t-ad-dns-ad_dns_dump

  - name: Account Review
    description: Checking for common misconfigurations related to ad accounts such as kerberoasting, as-rep roasting, 
      passwords quality, password never expires, inactive, passwords in description, etc
    tests:
      - name: Passwords in AD user description or other attributes
        techniques:
          - id: t-ad-account_review-passwords_in_user_attributes

      - name: User accounts with SPN and weak passwords (Kerberoasting)
        techniques:
          - id: t-ad-kerberos-kerberoasting
          - id: t-ad-credential_access-user_hashes_cracking
        findings:
          - id: f-ad-account_review-disabled_pre_authentication
                
      - name: Accounts with disabled Kerberos pre-authentication (AS-REP Roasting)
        techniques:
          - id: t-ad-kerberos-as_rep_roasting
          - id: t-ad-credential_access-user_hashes_cracking
          - id: t-ad-kerberos-as_rep_rc4_decryption_cve_2022_33679
        findings:
          - id: f-ad-account_review-disabled_pre_authentication
      
      - name: Accounts with "Password Not Required" Flag
        techniques:
          - id: t-ad-account_review-password_not_required
      
      - name: Pre-Windows 2000 computer accounts
        techniques:
          - id: t-ad-account_review-pre_windows_2000_accounts
      
      - name: Passwords Quality
        techniques:
          - id: t-ad-account_review-password_spray
      
      - name: Inactive Accounts
        techniques:
          - id: t-ad-account_review-inactive_accounts
      
      - name: Accounts with "Password Never Expires" Flag
        techniques:
          - id: t-ad-account_review-password_never_expires
      
      - name: Accounts In Privileged Groups
        techniques:
          - id: t-ad-privileged_groups-privileged_groups_enumeration
          - id: t-ad-privileged_groups-local_administrators
          - id: t-ad-privileged_groups-groups-rdp_privileges
      
      - name: Accounts with Reversible Password Encryption
        techniques:
          - id: t-ad-account_review-reversible_password_encryption
      
      - name: Temporary and Test Accounts
        techniques:
          - id: t-ad-account_review-temporary_accounts
      
      - name: Accounts That Have Never Logged In
        techniques:
          - id: t-ad-account_review-users_never_logged_in
  
  - name: LAPS
    tests:
      - name: LAPS Enumeration
        techniques:
          - id: t-ad-laps-laps_basics
  
  - name: Resources Review
    tests:
      - name: SMB
        techniques:
          - id: t-ad-smb-smb_null_session
          - id: t-ad-smb-smb_shares
          - id: t-ad-smb-smb_signing
          - id: t-ad-smb-smbv1
  
      - name: LDAP
        techniques:
          - id: t-ad-ldap-ldap_null_bind
          - id: t-ad-ldap-ldap_signing
          - id: t-ad-ldap-ldap_channel_binding
  
  - name: MSSQL
    tests:
      - name: MSSQL Attack Path
        techniques: 
            - id: t-ad-mssql-mssql_servers_enumeration
            - id: t-ad-mssql-linked_servers
  
  - name: ADCS
    tests:
      - name: ADCS Vulnerable Certificate Templates
        techniques:
          - id: t-ad-adcs-adcs_templates_enumeration
          - id: t-ad-adcs-adcs_esc1
  
  - name: NTLM Authentication / NTLM Relay attacks
    comments: Relay/coercion attacks
    tests:
      - name: NetNTLMv1 to Silver Ticket
        action: Force the domain hosts to authenticate using unsecure NetNTLMv1 protocol and crack the hashes
        techniques:
          - id: t-ad-ntlm-capture_ntlm_hashes
          - id: t-ad-ntlm-coerced_authentication_methods
          - id: t-ad-ntlm-netntlmv1_hashes_cracking
          - id: t-ad-kerberos-forging_silver_ticket

      - name: NTLM Relay to ADCS - ESC8
        techniques:
          - id: t-ad-ntlm-coerced-adcs_esc8
      
      - name: NTLM Relay to DCSync (NetNTLMv1 or Drop the MIC CVE)
        action: Force the domain hosts to authenticate and relay it to ldap
        techniques:
          - id: t-ad-ntlm-coerced-dcsync_abuse

      - name: NTLM Relay to RBCD abuse (NetNTLMv1 or Drop the MIC CVE)
        action: Force the domain hosts to authenticate and relay it to ldap
        techniques:
          - id: t-ad-ntlm-coerced-rbcd_abuse
      
      - name: NTLM Relay from WebDAV to Shadow Credentials
        action: Relay the server\workstation authentications (ususally workstations) to LDAP
        techniques:
          - id: t-ad-ntlm-coerced-webdav_shadow_credentials

  - name: ACL
    tests:
      - name: Discovery
        techniques:
          - id: t-ad-acl-acl_enumeration

      - name: ACL Abuse - Generic/All Write On Computers
        techniques:
          - id: t-ad-acl-acl_computers_generic_all_write

      - name: ACL Abuse - Generic/All Write/Owns On Groups
        techniques:
          - id: t-ad-acl-acl_groups_generic_all_write
          - id: t-ad-acl-acl_groups_owns

      - name: ACL Abuse - Generic/All Write On Users
        techniques:
          - id: t-ad-acl-acl_users_generic_all
          - id: t-ad-acl-acl_users_generic_write

  - name: GPO
    tests:
      - name: GPO
        techniques:
          - id: t-ad-acl-acl_gpo_create_new
          - id: t-ad-acl-acl_gpo_modify
          - id: t-ad-acl-acl_groups_owns

  - name: Domain/Forest Trusts
    tests:
      - name: Trusts Enumeration
        techniques:
          - id: t-ad-trusts-trusts_enumeration

      - name: Infra-Forest Exploitation
        techniques:
          - id: t-ad-trusts-infra_forest

      - name: Inter-Forest Exploitation
        techniques:
          - id: t-ad-trusts-sid_history
          - id: t-ad-trusts-foreign_groups
          - id: t-ad-trusts-tgt_delegation

  - name: Delegation
    tests:
      - name: Enumeration
        techniques:
          - id: t-ad-delegation-delegation_enumeration

      - name: Unconstrained delegation attack
        techniques:
          - id: t-ad-delegation-unconstrained_delegation_abuse

      - name: Constrained delegation attack
        techniques:
          - id: t-ad-delegation-constrained_delegation_any_protocol

  
      